Controllers films users
PaperAlex/java-filmorate pull request #2
Opened 2024-08-15 07:35 UTC by PaperAlex

2024-08-15 08:29 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за PR.

Отличная работа! :)

А давай посмотрим на наш код с точки зрения того, кто потом по логам будет разбираться в его работе. У логгера есть несколько уровней - error, info и пр. В принципе какие то тут правил нет, однако а давай приведем все к единому виду и посмотрим что получится, например вот так

- error - нештатные ситуации
- warn - штатные ошибки, та же валидация
- info - бизнес операции, плюс сюда в лог стоит включать какие то базовые идентификаторы, по которым можно будет сопоставлять строки лога с конкретными сущностями
- debug - дополнительная техническая информация, можно содержимое dto распечатывать, например (в реальном приложении только с этим аккуратно, не стоит так раскрывать какую то конфиденциальную информацию)

посмотри, пожалуйста, на логи с этой точки зрения, что получится :)

2024-08-15 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (name == null || name.isBlank() || name.isEmpty()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2024-08-15 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("Дата релиза — не раньше 28 декабря 1895 года");
log.error

А аналогичные ошибки у нас warn :)
Вот если так подумать, то ошибка - это когда что то пошло не так, а тут лишь ошибка валидации пользовательских данных - вполне себе штатная ситуация и она есть в нашей бизнес-логике,  наверно это все таки warn. error - это все таки что то непредвиденное, на что стоит обратить внимание, не удалось куда то подключиться, что то отправить, в общем какая то непредвиденная ошибка

2024-08-15 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Пользователь ввел некорректные данные - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
extends Exception

2024-08-15 08:29 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +        Set<ConstraintViolation<Film>> violationSet = validator.validate(film);
Далее идет блок из трех строк с проверкой валидации и он встречается и в других методах, а давай попробуем убрать дублирование и вынести  это в отдельный метод, например, assertValidation

2024-08-15 13:14 UTC, PaperAlex commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +        Set<ConstraintViolation<Film>> violationSet = validator.validate(film);
Спасибо. Все поправил )
Поторопился с коммитом, не заметил что тз еще на проверке. Остальные правки запушу когда закончится 1я проверка.

2024-08-15 18:42 UTC, EugeneLenkevich approved these changes
Это я оказывается кнопку отжать забыл :)

Все верно, на счет логов единственное можно еще вот так сделать
        log.info("Создание нового пользователя login: {}", user.getLogin());
        log.debug("user = {}", user);
        log.info("Новый пользователь успешно создан, id={}, login={}", ...);

Все ок, а работу шли обратно, надо тикет по статусам провернуть

2024-08-16 08:10 UTC, EugeneLenkevich approved these changes
Вообще в apache commons много всяких вспомогательных штук, бывает полезно https://www.baeldung.com/string-processing-commons-lang

2024-08-28 19:34 UTC, merged