Add database
PaperAlex/java-filmorate pull request #5
Opened 2024-09-25 19:10 UTC by PaperAlex

2024-09-26 08:51 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

Основные моменты 

- попробуй упросить код с Optional, синтаксический сахар, его цель сделать код проще для чтения, посмотрим на сколько он короче станет
- если получится то exist-запросы сделать бы, ну вообще, чем мы больше обработки ( имею в виду выборку, фильтрацию и пр данных) перекладываем на СУБД тем лучше, так как СУБД это делает более эффективно, но без фанатизма, главное постараться не тащить лишние данные :)

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws NotFoundException, ValidationException, SQLException {
SQLException

Вот не уверен что стоит так высоко прямо SQLException прокидывать, по сути дела мы в контракте вэб-сервиса декларируем пользователям (например, другим сервисам) нашего сервиса, что что надо обрабатывать именно такую ошибку. По хорошему эту бы ошибку так высоко не кидать, перехватывать (обрабатывать или заменять другой, уже бизнесовым исключением) на уровне сервиса или даже хранилища.

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          if (film.isEmpty()) {
film.isEmpty()

С Optional лучше вот так сделать, в более функциональном стиле

Film film = storage.findUser(....).orElseThrow(new NotFoundException(...))

https://struchkov.dev/blog/ru/optional-in-java/

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> findPopularFilms(Integer count) throws ValidationException {
А через аннотации не получается сделать проверку на null, что то типа @NotNull и пр :)
На отрицательнео число кстати будет такая же ошибка, про null.

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findFilmById(newFilm.getId()).isEmpty()) {
Можно кстати вот такой метод сделать

filmStorage.existsFilmById(newFilm.getId()): boolean

Можно попробовать вот такой запрос прикрутить, чутка эффективней будет и сам код наглядней 

https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Integer mpaCount = mpaStorage.findAllMpa().size();
mpaStorage.findAllMpa()

Мы тут все записи из таблицы вытаскиваем, это может быть опасно, если записей много, ну и не особо эффестивно. Однако, мы же можем запросом все это посчитать 

select count(id) from mpa

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        if (genre.isPresent()) {
Опять таки, это, с Optional, можно записать покороче. И посмотри, пожалуйста, аналогичные места :)

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.findUserById(userId).isEmpty() || userStorage.findUserById(friendId).isEmpty()) {
Вот с таким бы методом все бы стало покороче :)
userStorage.existsById(userId)

2024-09-26 08:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2024-09-27 03:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findFilmById(newFilm.getId()).isEmpty()) {
Чет слишком сложный запрос, предлагал только один метод заменить - filmStorage.existsFilmById :)

2024-09-27 03:41 UTC, EugeneLenkevich approved these changes
Ага, ок, пусть будет так, inmemory-реализацию можно было просто удалить чтобы не мешалась, если что в гите она есть 
Потом у нас будут спринговые репозитории, с ними запросы писать гораздо удобней, но общие принципы те же самые :)

2024-09-27 03:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        if (findUserById(userId).isEmpty() || findUserById(friendId).isEmpty()) {
findUserById(userId)
findUserById(friendId)

Вот к этим двум методам не получилось сделать аналогичную пару exists-методов с такими примерно запросами, тут не надо дополнительных сложностей, именно такие простые запросы ? 

`SELECT  EXISTS(SELECT 1 FROM user WHERE id = :userId);`

2024-09-27 03:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        Mpa mpa = mpaStorage.findMpaById(id).orElseThrow(() -> new NotFoundException("Rating does not exist"));
Часто подобное, как и другие стримы, разбивают на несколько строк, для удобства чтения, а то слишком много всего в строчке получается
```
Mpa mpa = mpaStorage.findMpaById(id)
    .orElseThrow(() -> new NotFoundException("Rating does not exist"));
```

2024-09-27 08:20 UTC, PaperAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        if (findUserById(userId).isEmpty() || findUserById(friendId).isEmpty()) {
Кажется разобрался)
`public boolean existFilmById(Long filmId) throws NotFoundException {
        String sql = "SELECT EXISTS(SELECT 1 FROM films WHERE film_id = ?);";
        if(Boolean.FALSE.equals(jdbcTemplate.queryForObject(sql, Boolean.class, filmId))) {
            throw new NotFoundException("Должен быть указан существующий id");
        }
        return true;
    }`

2024-10-08 11:42 UTC, merged